# GEOLOGICAL DATA ANLYSIS

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv(r"D:\Geoloc_DA\food_coded.csv")

In [4]:
df=pd.DataFrame(data)

In [5]:
print(data)

       GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0      2.4       2          1               430           NaN           315.0
1    3.654       1          1               610           3.0           420.0
2      3.3       1          1               720           4.0           420.0
3      3.2       1          1               430           3.0           420.0
4      3.5       1          1               720           2.0           420.0
..     ...     ...        ...               ...           ...             ...
120    3.5       1          1               610           4.0           420.0
121      3       1          1               265           2.0           315.0
122  3.882       1          1               720           NaN           420.0
123      3       2          1               720           4.0           420.0
124    3.9       1          1               430           NaN           315.0

     coffee                             comfort_food  \
0         1                                     none
1         2              chocolate, chips, ice cream
2         2          frozen yogurt, pizza, fast food
3         2         Pizza, Mac and cheese, ice cream
4         2             Ice cream, chocolate, chips
..      ...                                      ...
120       2  wine. mac and cheese, pizza, ice cream
121       2               Pizza / Wings / Cheesecake
122       1               rice, potato, seaweed soup
123       1             Mac n Cheese, Lasagna, Pizza
124       2             Chocolates, pizza, and Ritz.

                              comfort_food_reasons  \
0                            we dont have comfort
1                             Stress, bored, anger
2                                  stress, sadness
3                                          Boredom
4                       Stress, boredom, cravings
..                                             ...
120                           boredom and sadness
121                Loneliness / Homesick / Sadness
122                                        sadness
123  happiness, they are some of my favorite foods
124               hormones, Premenstrual syndrome.

     comfort_food_reasons_coded  ...  soup  sports  thai_food  \
0                           9.0  ...   1.0     1.0          1
1                           1.0  ...   1.0     1.0          2
2                           1.0  ...   1.0     2.0          5
3                           2.0  ...   1.0     2.0          5
4                           1.0  ...   1.0     1.0          4
..                          ...  ...   ...     ...        ...
120                         NaN  ...   1.0     1.0          5
121                         NaN  ...   1.0     NaN          4
122                         NaN  ...   1.0     2.0          5
123                         NaN  ...   2.0     2.0          1
124                         NaN  ...   1.0     2.0          2

    tortilla_calories  turkey_calories  type_sports veggies_day  vitamins  \
0              1165.0              345   car racing           5         1
1               725.0              690  Basketball            4         2
2              1165.0              500         none           5         1
3               725.0              690          NaN           3         1
4               940.0              500     Softball           4         2
..                ...              ...          ...         ...       ...
120             940.0              500     Softball           5         1
121             940.0              500  basketball            5         2
122             580.0              690         none           4         2
123             940.0              500          NaN           3         1
124             725.0              345          NaN           4         2

     waffle_calories                    weight
0               1315                       187
1                900                       155
2                900  I'm not answering this.
3               1315             Not sure, 240
4                760                       190
..               ...                       ...
120             1315                       156
121             1315                       180
122             1315                       120
123             1315                       135
124              575                       135

[125 rows x 61 columns]

## So at this stage we have successfully imported the data into the pandas, by hard coding

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          123 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB

In [7]:
df.describe()

,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,...,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,veggies_day,vitamins,waffle_calories
count,125.000000,125.000000,125.000000,106.000000,124.000000,125.00000,106.000000,122.000000,125.000000,108.000000,...,124.000000,124.000000,124.000000,123.000000,125.000000,124.000000,125.000000,125.000000,125.000000,125.000000
mean,1.392000,1.112000,577.320000,3.028302,505.241935,1.75200,2.698113,2.786885,2.688000,1.388889,...,2.806452,3.120968,1.217742,1.390244,3.336000,947.580645,555.040000,4.008000,1.512000,1073.400000
std,0.490161,0.316636,131.214156,0.639308,230.840506,0.43359,1.972042,1.038351,1.910987,0.974759,...,1.423824,1.115980,0.414385,0.489800,1.436528,202.090179,152.370379,1.081337,0.501867,248.667092
min,1.000000,1.000000,265.000000,2.000000,315.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,580.000000,345.000000,1.000000,1.000000,575.000000
25%,1.000000,1.000000,430.000000,3.000000,420.000000,2.00000,2.000000,2.000000,2.000000,1.000000,...,2.000000,2.000000,1.000000,1.000000,2.000000,725.000000,500.000000,3.000000,1.000000,900.000000
50%,1.000000,1.000000,610.000000,3.000000,420.000000,2.00000,2.000000,3.000000,2.000000,1.000000,...,3.000000,3.000000,1.000000,1.000000,3.000000,940.000000,500.000000,4.000000,2.000000,900.000000
75%,2.000000,1.000000,720.000000,3.000000,420.000000,2.00000,3.000000,3.000000,3.000000,1.000000,...,4.000000,4.000000,1.000000,2.000000,5.000000,1165.000000,690.000000,5.000000,2.000000,1315.000000
max,2.000000,2.000000,720.000000,4.000000,980.000000,2.00000,9.000000,5.000000,9.000000,6.000000,...,5.000000,6.000000,2.000000,2.000000,5.000000,1165.000000,850.000000,5.000000,2.000000,1315.000000

In [8]:
df.isnull().sum()

GPA                  2
Gender               0
breakfast            0
calories_chicken     0
calories_day        19
                    ..
type_sports         26
veggies_day          0
vitamins             0
waffle_calories      0
weight               2
Length: 61, dtype: int64

In [9]:
df.drop(columns=["GPA"])

,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,2.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,3.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,3.0,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,3.0,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,3.0,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,3.0,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [10]:
df.drop(columns=["comfort_food_reasons"])

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons_coded,cook,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,9.0,2.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream",1.0,3.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food",1.0,1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",2.0,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips",1.0,1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",NaN,3.0,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,NaN,3.0,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",NaN,3.0,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza",NaN,3.0,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.",NaN,NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [11]:
df.drop(columns=["mother_education" , "life_rewarding" , "ideal_diet" , "mother_profession" ])

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [12]:
df.drop(columns=["mother_education" , "life_rewarding" , "ideal_diet" , "mother_profession" ])

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          123 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          123 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB

In [16]:
df.drop(["GPA","comfort_food_reasons", "mother_education" , "life_rewarding" , "ideal_diet" , "mother_profession", "father_profession",
"food_childhood", "ideal_diet", "healthy_meal" , "meals_dinner_friend", "parents_cook"], axis=1, inplace=True)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 50 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Gender                        125 non-null    int64
 1   breakfast                     125 non-null    int64
 2   calories_chicken              125 non-null    int64
 3   calories_day                  106 non-null    float64
 4   calories_scone                124 non-null    float64
 5   coffee                        125 non-null    int64
 6   comfort_food                  124 non-null    object
 7   comfort_food_reasons_coded    106 non-null    float64
 8   cook                          122 non-null    float64
 9   comfort_food_reasons_coded.1  125 non-null    int64
 10  cuisine                       108 non-null    float64
 11  diet_current                  124 non-null    object
 12  diet_current_coded            125 non-null    int64
 13  drink                         123 non-null    float64
 14  eating_changes                122 non-null    object
 15  eating_changes_coded          125 non-null    int64
 16  eating_changes_coded1         125 non-null    int64
 17  eating_out                    125 non-null    int64
 18  employment                    116 non-null    float64
 19  ethnic_food                   125 non-null    int64
 20  exercise                      112 non-null    float64
 21  father_education              124 non-null    float64
 22  fav_cuisine                   123 non-null    object
 23  fav_cuisine_coded             125 non-null    int64
 24  fav_food                      123 non-null    float64
 25  fries                         125 non-null    int64
 26  fruit_day                     125 non-null    int64
 27  grade_level                   125 non-null    int64
 28  greek_food                    125 non-null    int64
 29  healthy_feeling               125 non-null    int64
 30  ideal_diet_coded              125 non-null    int64
 31  income                        124 non-null    float64
 32  indian_food                   125 non-null    int64
 33  italian_food                  125 non-null    int64
 34  marital_status                124 non-null    float64
 35  nutritional_check             125 non-null    int64
 36  on_off_campus                 124 non-null    float64
 37  pay_meal_out                  125 non-null    int64
 38  persian_food                  124 non-null    float64
 39  self_perception_weight        124 non-null    float64
 40  soup                          124 non-null    float64
 41  sports                        123 non-null    float64
 42  thai_food                     125 non-null    int64
 43  tortilla_calories             124 non-null    float64
 44  turkey_calories               125 non-null    int64
 45  type_sports                   99 non-null     object
 46  veggies_day                   125 non-null    int64
 47  vitamins                      125 non-null    int64
 48  waffle_calories               125 non-null    int64
 49  weight                        123 non-null    object
dtypes: float64(18), int64(26), object(6)
memory usage: 49.0+ KB

In [18]:
df.drop(["eating_changes"], axis=1, inplace=True)

In [19]:
df.isnull().sum()

Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
marital_status                   1
nutritional_check                0
on_off_campus                    1
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

In [22]:
df.drop(["type_sports"] ,axis=1, inplace=True)

In [25]:
print(df)

     Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0         2          1               430           NaN           315.0
1         1          1               610           3.0           420.0
2         1          1               720           4.0           420.0
3         1          1               430           3.0           420.0
4         1          1               720           2.0           420.0
..      ...        ...               ...           ...             ...
120       1          1               610           4.0           420.0
121       1          1               265           2.0           315.0
122       1          1               720           NaN           420.0
123       2          1               720           4.0           420.0
124       1          1               430           NaN           315.0

     coffee  comfort_food_reasons_coded  cook  comfort_food_reasons_coded.1  \
0         1                         9.0   2.0                             9
1         2                         1.0   3.0                             1
2         2                         1.0   1.0                             1
3         2                         2.0   2.0                             2
4         2                         1.0   1.0                             1
..      ...                         ...   ...                           ...
120       2                         NaN   3.0                             2
121       2                         NaN   3.0                             3
122       1                         NaN   3.0                             3
123       1                         NaN   3.0                             7
124       2                         NaN   NaN                             5

     cuisine  ... self_perception_weight  soup  sports  thai_food  \
0        NaN  ...                    3.0   1.0     1.0          1
1        1.0  ...                    3.0   1.0     1.0          2
2        3.0  ...                    6.0   1.0     2.0          5
3        2.0  ...                    5.0   1.0     2.0          5
4        2.0  ...                    4.0   1.0     1.0          4
..       ...  ...                    ...   ...     ...        ...
120      1.0  ...                    4.0   1.0     1.0          5
121      NaN  ...                    4.0   1.0     NaN          4
122      NaN  ...                    4.0   1.0     2.0          5
123      1.0  ...                    2.0   2.0     2.0          1
124      3.0  ...                    3.0   1.0     2.0          2

     tortilla_calories  turkey_calories  veggies_day  vitamins  \
0               1165.0              345            5         1
1                725.0              690            4         2
2               1165.0              500            5         1
3                725.0              690            3         1
4                940.0              500            4         2
..                 ...              ...          ...       ...
120              940.0              500            5         1
121              940.0              500            5         2
122              580.0              690            4         2
123              940.0              500            3         1
124              725.0              345            4         2

     waffle_calories                    weight
0               1315                       187
1                900                       155
2                900  I'm not answering this.
3               1315             Not sure, 240
4                760                       190
..               ...                       ...
120             1315                       156
121             1315                       180
122             1315                       120
123             1315                       135
124              575                       135

[125 rows x 47 columns]

In [28]:
print(df)

     Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0         2          1               430           NaN           315.0
1         1          1               610           3.0           420.0
2         1          1               720           4.0           420.0
3         1          1               430           3.0           420.0
4         1          1               720           2.0           420.0
..      ...        ...               ...           ...             ...
120       1          1               610           4.0           420.0
121       1          1               265           2.0           315.0
122       1          1               720           NaN           420.0
123       2          1               720           4.0           420.0
124       1          1               430           NaN           315.0

     coffee  comfort_food_reasons_coded  cook  comfort_food_reasons_coded.1  \
0         1                         9.0   2.0                             9
1         2                         1.0   3.0                             1
2         2                         1.0   1.0                             1
3         2                         2.0   2.0                             2
4         2                         1.0   1.0                             1
..      ...                         ...   ...                           ...
120       2                         NaN   3.0                             2
121       2                         NaN   3.0                             3
122       1                         NaN   3.0                             3
123       1                         NaN   3.0                             7
124       2                         NaN   NaN                             5

     cuisine  ... self_perception_weight  soup  sports  thai_food  \
0        NaN  ...                    3.0   1.0     1.0          1
1        1.0  ...                    3.0   1.0     1.0          2
2        3.0  ...                    6.0   1.0     2.0          5
3        2.0  ...                    5.0   1.0     2.0          5
4        2.0  ...                    4.0   1.0     1.0          4
..       ...  ...                    ...   ...     ...        ...
120      1.0  ...                    4.0   1.0     1.0          5
121      NaN  ...                    4.0   1.0     NaN          4
122      NaN  ...                    4.0   1.0     2.0          5
123      1.0  ...                    2.0   2.0     2.0          1
124      3.0  ...                    3.0   1.0     2.0          2

     tortilla_calories  turkey_calories  veggies_day  vitamins  \
0               1165.0              345            5         1
1                725.0              690            4         2
2               1165.0              500            5         1
3                725.0              690            3         1
4                940.0              500            4         2
..                 ...              ...          ...       ...
120              940.0              500            5         1
121              940.0              500            5         2
122              580.0              690            4         2
123              940.0              500            3         1
124              725.0              345            4         2

     waffle_calories                    weight
0               1315                       187
1                900                       155
2                900  I'm not answering this.
3               1315             Not sure, 240
4                760                       190
..               ...                       ...
120             1315                       156
121             1315                       180
122             1315                       120
123             1315                       135
124              575                       135

[125 rows x 47 columns]

In [31]:
df.columns

Index(['Gender', 'breakfast', 'calories_chicken', 'calories_day',
       'calories_scone', 'coffee', 'comfort_food_reasons_coded', 'cook',
       'comfort_food_reasons_coded.1', 'cuisine', 'diet_current',
       'diet_current_coded', 'drink', 'eating_changes_coded',
       'eating_changes_coded1', 'eating_out', 'employment', 'ethnic_food',
       'exercise', 'father_education', 'fav_cuisine', 'fav_cuisine_coded',
       'fav_food', 'fries', 'fruit_day', 'grade_level', 'greek_food',
       'healthy_feeling', 'ideal_diet_coded', 'income', 'indian_food',
       'italian_food', 'marital_status', 'nutritional_check', 'on_off_campus',
       'pay_meal_out', 'persian_food', 'self_perception_weight', 'soup',
       'sports', 'thai_food', 'tortilla_calories', 'turkey_calories',
       'veggies_day', 'vitamins', 'waffle_calories', 'weight'],
      dtype='object')

In [32]:
df.drop(
    [
        "calories_chicken",
        "waffle_calories",
        "turkey_calories",
        "greek_food",
        "indian_food",
        "italian_food",
        "persian_food",
        "thai_food",
        "fav_cuisine",
        "father_education",
        "marital_status",
        "weight",
        "Gender",
    ],
    axis=1,
    inplace=True,
)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   breakfast                     125 non-null    int64
 1   calories_day                  106 non-null    float64
 2   calories_scone                124 non-null    float64
 3   coffee                        125 non-null    int64
 4   comfort_food_reasons_coded    106 non-null    float64
 5   cook                          122 non-null    float64
 6   comfort_food_reasons_coded.1  125 non-null    int64
 7   cuisine                       108 non-null    float64
 8   diet_current                  124 non-null    object
 9   diet_current_coded            125 non-null    int64
 10  drink                         123 non-null    float64
 11  eating_changes_coded          125 non-null    int64
 12  eating_changes_coded1         125 non-null    int64
 13  eating_out                    125 non-null    int64
 14  employment                    116 non-null    float64
 15  ethnic_food                   125 non-null    int64
 16  exercise                      112 non-null    float64
 17  fav_cuisine_coded             125 non-null    int64
 18  fav_food                      123 non-null    float64
 19  fries                         125 non-null    int64
 20  fruit_day                     125 non-null    int64
 21  grade_level                   125 non-null    int64
 22  healthy_feeling               125 non-null    int64
 23  ideal_diet_coded              125 non-null    int64
 24  income                        124 non-null    float64
 25  nutritional_check             125 non-null    int64
 26  on_off_campus                 124 non-null    float64
 27  pay_meal_out                  125 non-null    int64
 28  self_perception_weight        124 non-null    float64
 29  soup                          124 non-null    float64
 30  sports                        123 non-null    float64
 31  tortilla_calories             124 non-null    float64
 32  veggies_day                   125 non-null    int64
 33  vitamins                      125 non-null    int64
dtypes: float64(15), int64(18), object(1)
memory usage: 33.3+ KB

In [34]:
df.columns

Index(['breakfast', 'calories_day', 'calories_scone', 'coffee',
       'comfort_food_reasons_coded', 'cook', 'comfort_food_reasons_coded.1',
       'cuisine', 'diet_current', 'diet_current_coded', 'drink',
       'eating_changes_coded', 'eating_changes_coded1', 'eating_out',
       'employment', 'ethnic_food', 'exercise', 'fav_cuisine_coded',
       'fav_food', 'fries', 'fruit_day', 'grade_level', 'healthy_feeling',
       'ideal_diet_coded', 'income', 'nutritional_check', 'on_off_campus',
       'pay_meal_out', 'self_perception_weight', 'soup', 'sports',
       'tortilla_calories', 'veggies_day', 'vitamins'],
      dtype='object')

In [42]:
print (df)

     coffee  cook  drink  eating_out  employment  exercise  fruit_day  income  \
0         1   2.0    1.0           3         3.0       1.0          5     5.0
1         2   3.0    2.0           2         2.0       1.0          4     4.0
2         2   1.0    1.0           2         3.0       2.0          5     6.0
3         2   2.0    2.0           2         3.0       3.0          4     6.0
4         2   1.0    2.0           2         2.0       1.0          4     6.0
..      ...   ...    ...         ...         ...       ...        ...     ...
120       2   3.0    2.0           2         1.0       2.0          5     4.0
121       2   3.0    1.0           4         3.0       2.0          4     2.0
122       1   3.0    1.0           3         3.0       2.0          4     2.0
123       1   3.0    2.0           5         2.0       1.0          5     4.0
124       2   NaN    1.0           1         2.0       2.0          3     5.0

     on_off_campus  pay_meal_out  sports  veggies_day
0              1.0             2     1.0            5
1              1.0             4     1.0            4
2              2.0             3     2.0            5
3              1.0             2     2.0            3
4              1.0             4     1.0            4
..             ...           ...     ...          ...
120            3.0             4     1.0            5
121            1.0             4     NaN            5
122            1.0             4     2.0            4
123            1.0             3     2.0            3
124            1.0             3     2.0            4

[125 rows x 12 columns]

### Now we switch from domain-based feature selection → data-based feature selection.

In [36]:
(df.isnull().mean() * 100).sort_values(ascending=False)

calories_day                    15.2
comfort_food_reasons_coded      15.2
cuisine                         13.6
exercise                        10.4
employment                       7.2
cook                             2.4
sports                           1.6
drink                            1.6
fav_food                         1.6
income                           0.8
diet_current                     0.8
tortilla_calories                0.8
soup                             0.8
self_perception_weight           0.8
calories_scone                   0.8
on_off_campus                    0.8
breakfast                        0.0
diet_current_coded               0.0
fav_cuisine_coded                0.0
ethnic_food                      0.0
eating_changes_coded1            0.0
eating_out                       0.0
eating_changes_coded             0.0
coffee                           0.0
comfort_food_reasons_coded.1     0.0
fruit_day                        0.0
nutritional_check                0.0
ideal_diet_coded                 0.0
healthy_feeling                  0.0
grade_level                      0.0
fries                            0.0
pay_meal_out                     0.0
veggies_day                      0.0
vitamins                         0.0
dtype: float64

In [40]:
df.drop(
    [
    'breakfast',
    'calories_day',
    'calories_scone',
    'comfort_food_reasons_coded',
    'comfort_food_reasons_coded.1',
    'cuisine',
    'diet_current',
    'diet_current_coded',
    'eating_changes_coded',
    'eating_changes_coded1',
    'ethnic_food',
    'fav_cuisine_coded',
    'fav_food',
    'fries',
    'grade_level',
    'healthy_feeling',
    'ideal_diet_coded',
    'nutritional_check',
    'self_perception_weight',
    'soup',
    'tortilla_calories',
    'vitamins'
] , inplace=True, axis =1)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   coffee         125 non-null    int64
 1   cook           122 non-null    float64
 2   drink          123 non-null    float64
 3   eating_out     125 non-null    int64
 4   employment     116 non-null    float64
 5   exercise       112 non-null    float64
 6   fruit_day      125 non-null    int64
 7   income         124 non-null    float64
 8   on_off_campus  124 non-null    float64
 9   pay_meal_out   125 non-null    int64
 10  sports         123 non-null    float64
 11  veggies_day    125 non-null    int64
dtypes: float64(7), int64(5)
memory usage: 11.8 KB

In [ ]:
pd.to_csv("Cleaned_GeoData.csv")